### ISSUE TITLE
Test play/stop workflows

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#318]
- [ ] play-pause-stop action cycles enough times (in random order) causes unresponsiveness and eventually after stopping cannot play again

**Comment by gidili** [comment]
@tarelli fixed by this? --> https://github.com/openworm/org.geppetto.frontend/commit/3c2acc8dc2fa44fb0ab9fd745cd37b887cd7e2fa

**Comment by tarelli** [comment]
Part of it yes, it still gets slower after many (something like 15) cycles
